// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwegnpxeoccjoqkmmwwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZWducHhlb2Njam9xa21td3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDU5OTIsImV4cCI6MjA2MDE4MTk5Mn0.ed0oM9fQmidyoecS4RK1FpzwLoBnx710GI1Ag9cXMEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);